"""add EmailStr

Revision ID: 0f89266ff6b6
Revises: 90cb5ba417cb
Create Date: 2025-03-05 16:38:14.139683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel    


# revision identifiers, used by Alembic.
revision: str = '0f89266ff6b6'
down_revision: Union[str, None] = '90cb5ba417cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
