"""hide db_url from alembic.ini

Revision ID: 49d318f3d7d7
Revises: b7fd2a4dfcdf
Create Date: 2025-03-01 23:50:19.972321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel    


# revision identifiers, used by Alembic.
revision: str = '49d318f3d7d7'
down_revision: Union[str, None] = 'b7fd2a4dfcdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
