"""add books db

Revision ID: 54a28f4d119a
Revises: 49d318f3d7d7
Create Date: 2025-03-05 12:22:37.023925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel    


# revision identifiers, used by Alembic.
revision: str = '54a28f4d119a'
down_revision: Union[str, None] = '49d318f3d7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    # ### end Alembic commands ###
