"""add relationship between user and book

Revision ID: 5a42bba035a4
Revises: a3fa1ab0bfa1
Create Date: 2025-03-07 11:39:44.353619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel    


# revision identifiers, used by Alembic.
revision: str = '5a42bba035a4'
down_revision: Union[str, None] = 'a3fa1ab0bfa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
