"""add reviews table

Revision ID: 7ba2f64751d9
Revises: 5a42bba035a4
Create Date: 2025-03-08 09:32:05.163205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel    


# revision identifiers, used by Alembic.
revision: str = '7ba2f64751d9'
down_revision: Union[str, None] = '5a42bba035a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uid', name='review_pkey')
    )
    # ### end Alembic commands ###
