"""set email to nullable = false

Revision ID: 90cb5ba417cb
Revises: e353b89473ef
Create Date: 2025-03-05 16:30:27.060676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel    


# revision identifiers, used by Alembic.
revision: str = '90cb5ba417cb'
down_revision: Union[str, None] = 'e353b89473ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'hashed_passord')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_passord', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
