"""add item table

Revision ID: b7fd2a4dfcdf
Revises: 39319920ca24
Create Date: 2025-03-01 23:05:51.283166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel    


# revision identifiers, used by Alembic.
revision: str = 'b7fd2a4dfcdf'
down_revision: Union[str, None] = '39319920ca24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
