"""add uuid4 to databse

Revision ID: c1f9b62a5e98
Revises: 8b647fe378bc
Create Date: 2025-03-05 15:19:57.716325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel    


# revision identifiers, used by Alembic.
revision: str = 'c1f9b62a5e98'
down_revision: Union[str, None] = '8b647fe378bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
