"""create models.py in reviews directory

Revision ID: daac36f4e66b
Revises: 7ba2f64751d9
Create Date: 2025-03-08 09:43:25.659292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel    


# revision identifiers, used by Alembic.
revision: str = 'daac36f4e66b'
down_revision: Union[str, None] = '7ba2f64751d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
