"""add users table

Revision ID: e353b89473ef
Revises: c1f9b62a5e98
Create Date: 2025-03-05 16:27:49.365528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel    
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e353b89473ef'
down_revision: Union[str, None] = 'c1f9b62a5e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hashed_passord', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
